steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "gs://bestbuy-kube/api-deployment.yaml", "/workspace/kubeconfig"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "nikolasleblanc/autosuggest_api:${TAG_NAME}", "."]
    id: "docker-build"

  - name: gcr.io/cloud-builders/kubectl
    env: ["KUBECONFIG=/workspace/kubeconfig", "CLOUDSDK_CONTAINER_CLUSTER=my-cluster", "CLOUDSDK_COMPUTE_ZONE=us-central1-b"]
    args: ["version"]

  - name: gcr.io/cloud-builders/kubectl
    env: ["KUBECONFIG=/workspace/kubeconfig"]
    args: ["apply", "-f", "/workspace/kubeconfig", "--validate=false"]