steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "gs://bestbuy-kube/api-deployment.yaml", "/workspace/kubeconfig"]

  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "nikolasleblanc/autosuggest_api:${TAG_NAME}", "."]
    id: "docker-build"

  - name: gcr.io/google_containers/hyperkube:v1.7.0
    env: ["KUBECONFIG=/workspace/kubeconfig"]
    entrypoint: "/hyperkube"
    args: ["kubectl", "apply", "-f", "/workspace/kubeconfig"]